name: sleep
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pandas
  - jupyter ipywidgets
  - tifffile
  - nbformat
  - plotly
  - pip:
    - pymysql
    - ydata-profilingy
    - h5py


